name: PrefixSwap
main: net.gnomeffinway.prefixswap.PrefixSwap
version: 0.1
author: GnomeffinWay
database: true

depends: [GroupManager,LogBlock,Vault,mcMMO]

commands:
    prefixswap:
        description: PrefixSwap root command
        aliases: ps
        usage: |
            /<command>
permissions:
    prefixswap.*:
        description: Gives access to all PrefixSwap commands
        children:
            prefixswap.list: true
    prefixswap.list:
        description: Lists player prefix options
        default: true